name: Build OpenClash for OpenWrt 23.05.5 on arm64 v8

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Free disk space
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/swift

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential flex bison g++ gawk gcc-multilib g++-multilib gettext git libfuse-dev libncurses5-dev libssl-dev python3 python3-pip python3-ply python3-pyelftools rsync unzip zlib1g-dev file wget subversion patch upx-ucl autoconf automake curl asciidoc binutils bzip2 lib32gcc-s1 libc6-dev-i386 uglifyjs msmtp texinfo libreadline-dev libglib2.0-dev xmlto libelf-dev libtool autopoint antlr3 gperf ccache swig coreutils haveged scons libpython3-dev jq

      - name: Clone OpenWrt source (使用--depth=1减少下载量)
        run: |
          git clone --depth=1 -b v23.05.5 https://github.com/openwrt/openwrt.git openwrt-source
          cd openwrt-source

      - name: Clone OpenClash source (使用--depth=1减少下载量)
        run: |
          cd openwrt-source
          mkdir -p feeds/packages/net
          git clone --depth=1 https://github.com/vernesong/OpenClash.git feeds/packages/net/openclash

      - name: Configure build
        run: |
          cd openwrt-source
          make defconfig ARCH=arm64 SUBARCH=arm64
          make menuconfig -o .config << 'EOF'
          CONFIG_PACKAGE_openclash=y
          CONFIG_PACKAGE_kmod-tun=y
          CONFIG_PACKAGE_kmod-inet-diag=y
          CONFIG_PACKAGE_kmod-nf-conntrack=y
          CONFIG_PACKAGE_kmod-nf-conntrack6=y
          CONFIG_PACKAGE_kmod-nf-flow=y
          CONFIG_PACKAGE_kmod-nf-ipt=y
          CONFIG_PACKAGE_kmod-nf-ipt6=y
          CONFIG_PACKAGE_kmod-nf-reject=y
          CONFIG_PACKAGE_kmod-nf-reject6=y
          CONFIG_PACKAGE_kmod-ipt-mod-tproxy=y
          CONFIG_PACKAGE_kmod-ip6tables-mod-tproxy=y
          EOF

      - name: Build OpenWrt with OpenClash
        run: |
          cd openwrt-source
          # 先更新feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          # 使用单线程构建，减少内存使用
          make -j1 V=s

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openclash-ipk-and-kmods
          path: |
            openwrt-source/bin/packages/arm64_cortex-a57_neon-vfpv4/openclash_*.ipk
            openwrt-source/bin/packages/arm64_cortex-a57_neon-vfpv4/kmod-*.ipk
          retention-days: 7
