name: Build OpenClash for OpenWrt 23.05.5 on arm64 v8

on:
  push:
    branches:
      - main

jobs:
  build:
    runs - on: ubuntu - latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          # 安装编译依赖
          sudo apt - get update
          sudo apt - get install - y build - essential flex bison g++ gawk gcc - multilib g++ - multilib gettext git libfuse - dev libncurses5 - dev libssl - dev python3 python3 - pip python3 - ply python3 - distutils python3 - pyelftools rsync unzip zlib1g - dev file wget subversion patch upx - ucl autoconf automake curl asciidoc binutils bzip2 lib32gcc - s1 libc6 - dev - i386 uglifyjs msmtp texinfo libreadline - dev libglib2.0 - dev xmlto libelf - dev libtool autopoint antlr3 gperf ccache swig coreutils haveged scons libpython3 - dev jq

      - name: Clone OpenWrt source
        run: |
          git clone https://github.com/openwrt/openwrt.git openwrt - source
          cd openwrt - source
          git checkout v23.05.5

      - name: Clone OpenClash source
        run: |
          cd openwrt - source
          mkdir - p feeds/packages/net
          git clone https://github.com/vernesong/OpenClash.git feeds/packages/net/openclash

      - name: Configure build
        run: |
          cd openwrt - source
          # 设置目标架构和内核配置
          make defconfig ARCH = arm64 SUBARCH = arm64
          # 或者使用更具体的目标配置（根据实际硬件调整）
          # make ath79 - generic_defconfig ARCH = arm64 SUBARCH = arm64

          # 添加OpenClash和相关kmods的配置
          make menuconfig - o .config << 'EOF'
          CONFIG_PACKAGE_openclash = y
          CONFIG_PACKAGE_kmod - tun = y
          CONFIG_PACKAGE_kmod - inet - diag = y
          CONFIG_PACKAGE_kmod - nf - conntrack = y
          CONFIG_PACKAGE_kmod - nf - conntrack6 = y
          CONFIG_PACKAGE_kmod - nf - flow = y
          CONFIG_PACKAGE_kmod - nf - ipt = y
          CONFIG_PACKAGE_kmod - nf - ipt6 = y
          CONFIG_PACKAGE_kmod - nf - reject = y
          CONFIG_PACKAGE_kmod - nf - reject6 = y
          CONFIG_PACKAGE_kmod - ipt - mod - tproxy = y
          CONFIG_PACKAGE_kmod - ip6tables - mod - tproxy = y
          EOF

      - name: Build OpenWrt with OpenClash
        run: |
          cd openwrt - source
          make - j$(nproc) V = s

      - name: Upload build artifacts
        uses: actions/upload - artifact@v4
        with:
          name: openclash - ipk - and - kmods
          path: openwrt - source/bin/packages/arm64_cortex - a57_neon - vfpv4/openclash_*.ipk openwrt - source/bin/packages/arm64_cortex - a57_neon - vfpv4/kmod - *.ipk
